### ISSUE TITLE
Social icons?

### ISSUE THREAD

**Issue by alexlangberg** [somerandomdude/Iconic#26]
Hi

Thanks a lot for all these icons, the flexibility is so much better than with other sets! This isn't really an issue but I'd like to hear if there are any plans to implement social icons too? That would make this icon set perfect and remove the need for any other sets.

Best,
Alex

**Comment by Kalus** [comment]
I'm willing to help add social media icons. I'm thinking three styles: Circle, Box with rounded corners, and a plain social icon. I'll start with Facebook and Twitter. Someone let me know if they're interested in other social icons, or if they'd like to join in. I'm forking now.

**Comment by MaPePeR** [comment]
The problem is, that you are not allowed to modify the icon-style/use an alternative icon for facebook, twitter, etc. 
Even GitHub is very strict about that.

**Comment by danielepiccone** [comment]
We can consider the monochome version of each logo, or maybe we can add just the glyphs, Fontawesome has those . Anyway i am willing to help in this, really miss social media pictorgrams in Iconic.

**Comment by somerandomdude** [comment]
Hey guys, apologies for the delay in responding. I've intentionally left logos out of Iconic because I never felt they belonged in the icon set. I think providing vector logos for influential online properties is useful, but it flirts with intellectual property and I'd like to avoid it. Especially as an open source project, making vector versions of logos "open" seems strange. 

On the general subject of Iconic, there's a lot happening behind the scenes. I can't wait to share some pretty big news.

**Comment by Bengt** [comment]
Social and other company icons are subject of other icon sets, already. A quick search brought these up:
-   [danleech/simple-icons](https://github.com/danleech/simple-icons)
-   [adamfairhead/webicons](https://github.com/adamfairhead/webicons)

Since the sets of icons of these projects and Iconis are disjunct, they both have they complement each other without overlap. One can combine this set with a plain logo icon set like "Simple Icons" as seamlessly as possible, already. So I do not see the necessity to include social respectively company icons in this icon set. Also, these icons will most likely not fit into to grid-based design of Iconic.

**Comment by somerandomdude** [comment]
Agreed
P.J.

**Comment by alexlangberg** [comment]
No longer maintained. Closing.
